//This file is automatically generated. DO NOT EDIT!
using System;
using RobotRaconteur;
using System.Collections.Generic;

namespace experimental.createwebcam
{
public class WebcamImage
{
    public int width;
    public int height;
    public int step;
    public byte[] data;
}

public class WebcamImage_size
{
    public int width;
    public int height;
    public int step;
}

[RobotRaconteurServiceObjectInterface()]
public interface Webcam
{
    string Name { get; set; }
    WebcamImage CaptureFrame();
    void StartStreaming();
    void StopStreaming();
    WebcamImage_size CaptureFrameToBuffer();
    Pipe<WebcamImage> FrameStream{ get; set; }
    ArrayMemory<byte> buffer { get; set; }
    MultiDimArrayMemory<byte> multidimbuffer { get; set; }
}

[RobotRaconteurServiceObjectInterface()]
public interface WebcamHost
{
    Dictionary<int,string> WebcamNames { get; set; }
    Webcam get_Webcams(int ind);
}

}
